composition/legacy_behavior.md
custom_elements_attributes/proposal.md
install/tutorial_2-0.md
install/tutorial_6-x.md
manifest.xml
pose_frame_semantics/proposal.md
pose_frame_semantics/tutorial.md
specify_pose/tutorial.md

Preview: http://sdformat.org/tutorials?branch=update_bitbucket_links
Most of these links are directly "ported" to GitHub, but I noticed that a reference to world.sdf in `pose_frame_semantics/tutorial.md` had an incorrect line number, so I corrected it.

Migrate bitbucket links to GitHub

---

developers/proposal_format.md

I think the `#` inside the comment tags on line 28 is actually breaking up the comment, and for some reason the line ends up in the table of contents side bar:

HTML comment rendering in t.o.c.

---

developers/roadmap.md

Based on plan in https://github.com/osrf/sdformat/issues/278.

roadmap: add plan for libsdformat10, 11

---

pose_frame_semantics/proposal.md

Add links in the parsing stages of the SDFormat 1.7 proposal to the code that implements those parsing stages in libsdformat9.
Preview: http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&cat=pose_semantics_docs&branch=proposal_stages_code_links#1-model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/28)

SDFormat 1.7 parsing stages: add links to libsdformat9 code

---

composition/proposal.md

This copies the parsing stages from the [Pose Frame Semantics Proposal](http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&cat=pose_semantics_docs&#phases-of-parsing-kinematics) (recently updated by #28) to the composition proposal, so that we can update the parsing stages with each aspect of the proposal.
Preview: http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&branch=copy_parsing_stages_to_composition_proposal#1-6-proposed-parsing-stages

Copy 1.7 parsing stages to composition proposal

---

composition/proposal.md

This updates the proposed SDFormat 1.8 parsing stages to support specifying frames in `//joint/child` and `//joint/parent`. This involves some updates to the wording and re-ordering some steps to ensure that all graph vertices are added before connecting an edge between a joint and its child frame. The code links are updated as well to point to the changes in https://github.com/osrf/sdformat/pull/304.
This is a draft PR targeting #29; I will take it out of draft state and retarget to master once that is merged.
The markdown preview is nice on this page, but you can also preview it on sdformat.org:
* http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&branch=joint_parent_child_frame_parsing#1-6-proposed-parsing-stages
---
This change is [<img …

Proposed 1.8 parsing stages: support joint parent/child frames

---

composition/proposal.md

For more background, see existing proposal:
https://github.com/osrf/sdf_tutorials/blob/251b28804a6e79ac1b89001b8fd0036bc07e0d7d/composition/proposal.md
Basically, this interface API is to allow included models to either (a) be parsed by `libsdformat` (and thus must be completely understood) or (b) be parsed by the downstream library, with the absolute minimum information passed back to `libsdformat` for links and frames (for posturing and connecting joints).
Motivational WIP usage of phantom API:
https://github.com/RobotLocomotion/drake/pull/13128
(Branch ported from BitBucket)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/3)

composition/proposal: Expand on interface-type API

---

composition/legacy_behavior.md
composition/proposal.md
pose_frame_semantics/proposal.md

Per comment here:
https://github.com/osrf/sdformat/pull/316#pullrequestreview-454551049
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/36)

composition/proposal: Permit nested canonical links

---

composition/legacy_behavior.md
pose_frame_semantics/proposal.md

This adds support for nested models to the SDFormat 1.7 proposal. The spec supports nested models, so even though it wasn't included in libsdformat 9.2 and earlier, we could consider adding it now.
This currently has only updated the parsing stages. It is a draft until the prose is updated as well for consistency.
http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&branch=nested_model_dom_9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/34)

Add nested models to SDFormat 1.7 proposal

---

pose_frame_semantics/proposal.md

Add parsing stage for identifying the canonical
link of a model with 3 steps:
1. If //model/@canonical_link is specified, choose that link.
2. If //model/@canonical_link is not specified, and the model
has at least one link, choose the first link.
3. Otherwise, chose the canonical link of the first nested
model. This may be a recursive process if there are multiple
levels of nested models without links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/40)

Parsing stages for nested canonical links

---

composition/proposal.md

Resolves https://github.com/osrf/sdformat/issues/335
Preview: http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&branch=model_placement_frame#1-4-4-placement-frame-model-placement_frame-and-include-placement_frame
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/42)

Add //model/@placement_frame to proposal

---

composition/legacy_behavior.md
composition/proposal.md

As motivated here: https://github.com/osrf/sdformat/pull/355#pullrequestreview-486246061
Towards osrf/sdformat#342
Resolves #39
Preview:
http://sdformat.org/tutorials?tut=composition_proposal&branch=feature-sdformat-pr355-up-convert&repo=https%3A%2F%2Fgithub.com%2FEricCousineau-TRI%2Fsdf_tutorials-1#1-4-7-up-converting-flattened-models
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/41)

composition: Add section for up-converting unflattened models

---

composition/legacy_behavior_1-5.md
manifest.xml

Copied legacy_behavior.md from 66d3d885037 (before #41) to legacy_behavior_1-5.md as discussed in https://github.com/osrf/sdf_tutorials/pull/41#pullrequestreview-495991631.
Preview:
* 1.5: http://sdformat.org/tutorials?tut=composition&ver=1.5&cat=specification&branch=legacy_behavior_1-5#libsdformats-implementation-of-include-in-models
* 1.7: http://sdformat.org/tutorials?tut=composition&ver=1.7&cat=specification&branch=legacy_behavior_1-5#libsdformats-implementation-of-include-in-models

Add 1.5 version of legacy_behavior docs

---

composition/proposal.md

Also update unnesting output to SDFormat 1.8
\cc @azeey @jennuine per VC

composition: For unnesting, state that `@canonical_link` will always be specified

---

developers/roadmap.md

In [Roadmap](http://sdformat.org/tutorials?tut=roadmap&cat=developers&), changed **planned** to **released** for Dome and Edifice

Update roadmap for Dome & Edifice

---

developers/roadmap.md

In [Roadmap](http://sdformat.org/tutorials?tut=roadmap&cat=developers&), added **planned** Fortress `libsdformat12` and `SDFormat 1.9` specification
**Note to maintainers**: Remember to use **Squash-Merge**

Roadmap: add libsdformat12 for Fortress

---

specify_pose/proposal.md

This proposes some changes to #56, specifically adding motivation for quaternions as a supported rotation format.

Suggestions for #56: add motivation for quaternions as rotation format

---

specify_pose/proposal.md

This updates the proposal to reflect the accepted implementation in https://github.com/ignitionrobotics/sdformat/pull/589 and the proposed implementation in https://github.com/ignitionrobotics/sdformat/pull/690. 
Preview: http://sdformat.org/tutorials?tut=better_pose_proposal&cat=pose_semantics_docs&branch=azeey%2Fbetter_pose_update

Update document to better reflect proposed and accepted implementations

---

manifest.xml

Minor fixes to proposals in `manifest.xml`
* Fix version number of better pose proposal to 1.9 to match implementation
* Reorder proposals to preserve number sorting
http://sdformat.org/tutorials?cat=pose_semantics_docs&branch=scpeters/fix_proposal_order_version

manifest.xml: fix proposal version and order

---

pose_frame_semantics/tutorial.md
pose_frame_semantics/tutorial_1-5.md

This adds to the existing documentation of pose and frame semantics for version 1.5 of the spec. The default frame in which `//joint/axis/xyz` unit vectors are expressed changed from SDFormat 1.4 to 1.5, and the `//axis/use_parent_model_frame` boolean element was added to parameterize this behavior change.
Preview: http://sdformat.org/tutorials?tut=pose_frame_semantics&ver=1.5&branch=scpeters/use_parent_model_frame#specifying-joint-axes-in-sdf-1-4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazebosim/sdf_tutorials/75)

Doc: joint axis unit vector expressed-in frames

---

pose_frame_semantics/proposal.md

Adds missing valid values to attribute checking portion of parsing stages
In the parsing stages for checking `@attached_to` and `@relative_to` attribute values, clarify that `__model__` and `world` can be used explicitly in the appropriate context.
Preview: http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&branch=scpeters/explicit_model_world_references#1-model

Frame semantics parsing stages: clarify validity of __model__, world

---

manifest.xml
python/tutorial_13.md

Signed-off-by: ahcorde <ahcorde@gmail.com>
Added Python tutorial

Added Python tutorial

---

mimic_joint/proposal.md

This is an edit to the ongoing proposal related to mimic joints : https://github.com/gazebosim/sdf_tutorials/pull/62
It aims to add a ``mimic`` tag to ``//joint/axis/mimic`` to specify the name and multiplier associated with a second joint, that should mimic the behavior of the first one.

Mimic joints : support ``mimic`` tag in ``//joint/axis/``

---

added_mass/proposal.md
manifest.xml

* Part of https://github.com/gazebosim/gz-sim/issues/1462
I'm looking for early feedback on the proposal. I'm planning to circulate this with the [ROS Maritime Working Group](https://discourse.ros.org/t/new-working-group-proposal-maritime-robotics/23832) for feedback after the initial review.
Rendered preview:
http://sdformat.org/tutorials?tut=added_mass_proposal&branch=chapulina/added_mass

Proposal for hydrodynamic added mass

---

composition/merge_proposal.md

Extends model merge-include to worlds. The merge mechanism should be exactly the same except the type of elements that are allowed to be merged.
[Preview](http://sdformat.org/tutorials?tut=composition_merge_proposal&cat=pose_semantics_docs&branch=azeey%2Fworld_merge_include)

Add amendment for world merge-include

---

manifest.xml
urdf/examples/disable_fixed_joint_lumping_example.urdf
urdf/examples/fixed_joint_lumping_example.urdf
urdf/examples/friction_example.urdf
urdf/examples/joint_example.urdf
urdf/examples/link_ref_example.urdf
urdf/examples/material_example.urdf
urdf/examples/material_visual_example.urdf
urdf/examples/no_ref_example.urdf
urdf/examples/preserve_fixed_joint_example.urdf
urdf/examples/visual_example.urdf
urdf/sdf_extensions.md

There is good documentation for the `<gazebo>` tag at https://classic.gazebosim.org/tutorials?tut=ros_urdf&cat=connect_ros, but it is presented in a tutorial format and is missing some concepts and explanations. This is an attempt to document the current behavior and provide an explanation about fixed joint lumping.
[Preview](http://sdformat.org/tutorials?tut=sdformat_urdf_extensions&cat=specification&branch=urdf_sdf_extension&repo=https%3A%2F%2Fgithub.com%2Fazeey%2Fsdf_tutorials)

Add documentation for SDFormat/Gazebo extension to URDF

---

urdf/sdf_extensions.md

Fixes URLs pointing to my branch in PR #88.
[Preview](http://sdformat.org/tutorials?tut=sdformat_urdf_extensions&cat=specification&branch=url_fixes&repo=https%3A%2F%2Fgithub.com%2Fazeey%2Fsdf_tutorials)

Fix include URLs for SDFormat extension to URDF tutorial

---

pose_frame_semantics/proposal.md

Fixes a link to an incorrect page in the Pose Frame Semantics proposal. Link to version 1.5 of the documentation page, which has the `Parent Frames in URDF section`.
* Current broken link: http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&cat=pose_semantics_docs&#1-1-parity-with-urdf-using-pose-relative_to
* Fixed link in this branch: http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&cat=pose_semantics_docs&branch=scpeters/fix_urdf_proposal_link#1-1-parity-with-urdf-using-pose-relative_to

Fix link in frame semantics proposal

---

interoperability_formats/tutorial.md

Updated invalid [`gz-usd`](https://github.com/gazebosim/gz-usd) links from a deleted branch to `main`. Furthermore, updated the link to the new homepage of USD (OpenUSD).

Fix broken links to gz-usd

---

auto_inertial_params/proposal.md
manifest.xml

This proposal is in regard to GSoC'23 Project titled: "Automatically Computing Moments of Inerial for SDFormat Links"
The proposal suggests adding new attributes and elements to support the automatic calculation of Moments of Inertia and Products of Inertia for a link in SDFormat. The proposal targets SDFormat 1.11 and `libsdformat14`. 
http://sdformat.org/tutorials?tut=auto_inertial_params_proposal&cat=pose_semantics_docs&branch=jasmeet%2Fauto_inertial_params&repo=https%3A%2F%2Fgithub.com%2Fjasmeet0915%2Fsdf_tutorials

Proposal for Automatic Calculation of Moments of Inertia for SDFormat Links

---

auto_inertial_params/proposal.md

**See diff without whitespace:**
https://github.com/gazebosim/sdf_tutorials/pull/100/files?w=1
Added a note to mention how inertial params are computed if mass is specified.

Add note about mass in auto inertial proposal
